#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x575159689BEFB442 (dev@fpcomplete.com)
#
Name     : stack
Version  : 2.9.3
Release  : 19
URL      : https://github.com/commercialhaskell/stack/releases/download/v2.9.3/stack-2.9.3-linux-x86_64.tar.gz
Source0  : https://github.com/commercialhaskell/stack/releases/download/v2.9.3/stack-2.9.3-linux-x86_64.tar.gz
Source1  : https://github.com/commercialhaskell/stack/releases/download/v2.9.3/stack-2.9.3-linux-x86_64.tar.gz.asc
Summary  : The Haskell Tool Stack
Group    : Development/Tools
License  : BSD-3-Clause
Requires: stack-bin = %{version}-%{release}
Requires: stack-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-Makefile-with-install-target.patch

%description
Stack is a cross-platform program for developing Haskell projects. It is
intended for Haskellers both new and experienced.

%package bin
Summary: bin components for the stack package.
Group: Binaries
Requires: stack-license = %{version}-%{release}

%description bin
bin components for the stack package.


%package license
Summary: license components for the stack package.
Group: Default

%description license
license components for the stack package.


%prep
%setup -q -n stack-2.9.3-linux-x86_64
cd %{_builddir}/stack-2.9.3-linux-x86_64
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1675289566
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1675289566
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/stack
cp %{_builddir}/stack-%{version}-linux-x86_64/LICENSE %{buildroot}/usr/share/package-licenses/stack/c2e88ce3ecac0bf589f7f22f56a78cdf7e026589 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/stack

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/stack/c2e88ce3ecac0bf589f7f22f56a78cdf7e026589
